spring:
  application:
    name: InvoiceService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: postgres
    password: ${DB_PASS:invoice_password}